PREFIX ps: <https://w3id.org/payswarm#>
prefix geo:      <http://www.opengis.net/ont/geosparql#> 
prefix p:        <http://www.wikidata.org/prop/> 
prefix pq:       <http://www.wikidata.org/prop/qualifier/> 
prefix pr:       <http://www.wikidata.org/prop/reference/> 
prefix prov:     <http://www.w3.org/ns/prov#> 
prefix ps:       <http://www.wikidata.org/prop/statement/> 
prefix rdf:      <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix rdfs:     <http://www.w3.org/2000/01/rdf-schema#> 
prefix schema:   <http://schema.org/> 
prefix skos:     <http://www.w3.org/2004/02/skos/core#> 
prefix wd:       <http://www.wikidata.org/entity/> 
prefix wdno:     <http://www.wikidata.org/prop/novalue/> 
prefix wds:      <http://www.wikidata.org/entity/statement/> 
prefix wdt:      <http://www.wikidata.org/prop/direct/> 
prefix wikibase: <http://wikiba.se/ontology#> 
prefix xsd:      <http://www.w3.org/2001/XMLSchema#> 


SELECT ?x ?xLabel ?countP361 WHERE {
  ?x wdt:P31 wd:Q4936952  .
 { select (count(?y) as ?countP361) where { 
     ?x wdt:P361 ?y 
   } 
 } 
            
 Optional { ?x rdfs:label ?xLabel }
 filter(
    lang(?xLabel)='en' 
  )
}